name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build and push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: ${{ secrets.DOCKER_HUB_USERNAME }}/marketplace-backend
        tags: latest
        registry: docker.io
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        dockerfile: /backend/web/Dockerfile
